"""Request signing via the vendored ``edge_core`` WASM module.

The iGPSport private API requires an ``x-signature`` (plus ``x-nonce`` /
``x-timestamp`` / ``x-access-key``) generated by a Rust→WASM module shipped by
the web frontend. We vendor the binary and drive it with ``wasmtime`` rather
than re-implementing the RSA/SHA-256 algorithm.

Handshake (see reverse-engineering notes §3):
1. GET ``/service/edge-core/api/public/key`` (unsigned) -> 256-byte secret_key
2. ``init_session_key(secret_key)``
3. per request: ``generate_signature(method, full_path, timestamp, nonce, body)``

This is a faithful Python port of the wasm-bindgen glue the frontend uses
(originally reproduced in the Node PoC ``scratch/signtest.mjs``). The WASM
module imports two ``wbg`` helpers (an externref-table initializer and a
string-cast helper) and exports ``init_session_key`` / ``generate_signature``
plus the standard ``__wbindgen_malloc`` / ``__wbindgen_free`` allocator.
"""

from __future__ import annotations

import base64
import threading
from importlib import resources

import wasmtime

from ..exceptions import IGPSportError

WASM_RESOURCE = "edge_core_wasm_bg.wasm"

_INIT_TABLE_IMPORT = "__wbindgen_init_externref_table"
_CAST_IMPORT = "__wbindgen_cast_2241b6af4c4b2941"


class SignerError(IGPSportError):
    """The WASM signer failed to initialize a session key or sign a request."""


def wasm_bytes() -> bytes:
    """Return the vendored WASM module bytes."""
    return resources.files(__package__).joinpath(WASM_RESOURCE).read_bytes()


def _decode_secret_key(secret_key_b64: str) -> bytes:
    """Mirror the frontend ``cU``: tolerant (url-safe) base64 decode."""
    s = secret_key_b64.strip().replace("-", "+").replace("_", "/")
    s += "=" * ((4 - len(s) % 4) % 4)
    return base64.b64decode(s)


class WasmSigner:
    """Drives the vendored WASM module to produce request signatures.

    Not thread-safe internally; all access is serialized via an instance lock,
    so a single signer can be shared across the (sync) client safely.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        config = wasmtime.Config()
        config.wasm_reference_types = True
        self._engine = wasmtime.Engine(config)
        self._store = wasmtime.Store(self._engine)
        self._module = wasmtime.Module(self._engine, wasm_bytes())
        self._instance: wasmtime.Instance | None = None
        self._exports: wasmtime.Exports | None = None
        self._memory: wasmtime.Memory | None = None
        self._table: wasmtime.Table | None = None
        self._session_ready = False
        self._instantiate()

    # -- WASM plumbing -----------------------------------------------------

    def _instantiate(self) -> None:
        import_types = {(i.module, i.name): i.type for i in self._module.imports}

        init_table_func = wasmtime.Func(
            self._store,
            import_types[("wbg", _INIT_TABLE_IMPORT)],
            self._init_externref_table,
        )
        cast_func = wasmtime.Func(
            self._store,
            import_types[("wbg", _CAST_IMPORT)],
            self._cast_str,
        )

        instance = wasmtime.Instance(self._store, self._module, [init_table_func, cast_func])
        exports = instance.exports(self._store)
        self._instance = instance
        self._exports = exports
        self._memory = exports["memory"]
        self._table = exports["__wbindgen_externrefs"]

        start = exports.get("__wbindgen_start")
        if start is not None:
            start(self._store)

    def _init_externref_table(self, *_: object) -> None:
        # Replicates the wasm-bindgen heap sentinels: index 0 = undefined,
        # then [undefined, null, true, false] at the freshly grown slots.
        table = self._table
        assert table is not None
        base = table.grow(self._store, 4, wasmtime.Val.ref_null(wasmtime.ValType.externref()))
        table.set(self._store, 0, wasmtime.Val.externref(None))
        table.set(self._store, base + 0, wasmtime.Val.externref(None))
        table.set(self._store, base + 1, wasmtime.Val.externref(None))
        table.set(self._store, base + 2, wasmtime.Val.externref(True))
        table.set(self._store, base + 3, wasmtime.Val.externref(False))

    def _cast_str(self, ptr: int, length: int) -> wasmtime.Val:
        # Boxes a Rust UTF-8 string (error path) into a host value.
        data = self._read(ptr, length)
        return wasmtime.Val.externref(data.decode("utf-8", "replace"))

    def _read(self, ptr: int, length: int) -> bytes:
        assert self._memory is not None
        return self._memory.read(self._store, ptr, ptr + length)

    def _malloc(self, data: bytes) -> tuple[int, int]:
        assert self._exports is not None and self._memory is not None
        ptr = self._exports["__wbindgen_malloc"](self._store, len(data), 1)
        if data:
            self._memory.write(self._store, data, ptr)
        return ptr, len(data)

    def _free(self, ptr: int, length: int) -> None:
        assert self._exports is not None
        self._exports["__wbindgen_free"](self._store, ptr, length, 1)

    # -- public API --------------------------------------------------------

    def init_session_key(self, secret_key_b64: str) -> None:
        """Inject the server-issued session key. Call after each ``/public/key``."""
        key = _decode_secret_key(secret_key_b64)
        with self._lock:
            assert self._exports is not None
            ptr, length = self._malloc(key)
            result = self._exports["init_session_key"](self._store, ptr, length)
            ok, _unused, err_flag = result
            if err_flag or not ok:
                raise SignerError("WASM init_session_key failed (bad secret_key?)")
            self._session_ready = True

    def generate_signature(
        self,
        method: str,
        full_path: str,
        timestamp: str,
        nonce: str,
        body: str,
    ) -> str:
        """Sign one request. ``body`` is the serialized JSON ("" for GET)."""
        with self._lock:
            if not self._session_ready:
                raise SignerError("generate_signature called before init_session_key")
            assert self._exports is not None
            allocated: list[tuple[int, int]] = []
            args: list[int] = []
            try:
                for text in (method, full_path, timestamp, nonce):
                    p_ptr, p_len = self._malloc(text.encode("utf-8"))
                    allocated.append((p_ptr, p_len))
                    args.extend((p_ptr, p_len))
                p_ptr, p_len = self._malloc(body.encode("utf-8"))
                allocated.append((p_ptr, p_len))
                args.extend((p_ptr, p_len))

                ptr, length, _err_ptr, err_flag = self._exports["generate_signature"](
                    self._store, *args
                )
                if err_flag:
                    raise SignerError("WASM generate_signature failed")
                signature = self._read(ptr, length).decode("utf-8")
                self._free(ptr, length)
                return signature
            finally:
                for p_ptr, p_len in allocated:
                    self._free(p_ptr, p_len)
